apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bis-platform
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - services.yaml
commonLabels:
  app.kubernetes.io/part-of: bis-platform
images:
  - name: bis-identity-service
    newName: ghcr.io/YOUR_ORG/bis-identity-service
    newTag: latest
  - name: bis-certification-service
    newName: ghcr.io/YOUR_ORG/bis-certification-service
    newTag: latest
  - name: bis-laboratory-service
    newName: ghcr.io/YOUR_ORG/bis-laboratory-service
    newTag: latest
  - name: bis-operations-service
    newName: ghcr.io/YOUR_ORG/bis-operations-service
    newTag: latest
  - name: bis-integration-service
    newName: ghcr.io/YOUR_ORG/bis-integration-service
    newTag: latest
  - name: bis-master-data-service
    newName: ghcr.io/YOUR_ORG/bis-master-data-service
    newTag: latest
