apiVersion: v1
kind: Secret
metadata:
  name: bis-platform-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: __REPLACE_WITH_DB_USERNAME__
  SPRING_DATASOURCE_PASSWORD: __REPLACE_WITH_DB_PASSWORD__
