apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bis-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amitbansal26/bis-fresh.git
    targetRevision: main
    path: deploy/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: bis-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
