package in.gov.bis.platform.common.workflow;

public enum ApplicationStatus {
    DRAFT, SUBMITTED, UNDER_SCRUTINY, PENDING_DOCUMENTS, UNDER_REVIEW,
    INSPECTION_SCHEDULED, INSPECTION_COMPLETED, APPROVED, REJECTED,
    WITHDRAWN, CANCELLED, EXPIRED, ON_HOLD, REVOKED
}
