package in.gov.bis.platform.common.workflow;

public enum WorkflowAction {
    SUBMIT, SCRUTINIZE, REQUEST_DOCUMENTS, UPLOAD_DOCUMENTS, ASSIGN_INSPECTOR,
    SCHEDULE_INSPECTION, COMPLETE_INSPECTION, APPROVE, REJECT, WITHDRAW, CANCEL,
    PUT_ON_HOLD, RESUME, REVOKE, REOPEN
}
